# Default Spring Profile
server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.kairns: DEBUG

app:
  users-service:
    host: localhost
    port: 8081
  workouts-service:
    host: localhost
    port: 8082
  meals-service:
    host: localhost
    port: 8083
  dailylogs-service:
    host: localhost
    port: 8084

---

spring:
  config:
    activate:
      on-profile: docker

server.port: 8080

app:
  users-service:
    #must match Docker host name
    host: users-service
    port: 8081
  workouts-service:
    host: workouts-service
    port: 8082
  meals-service:
    host: meals-service
    port: 8083
  dailylogs-service:
    host: dailylogs-service
    port: 8084